on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy in Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/marisembuh/marisembuh-fe
            git pull
            npm install
            npm run build
            sudo rm -r /var/www/html/marisembuh/*
            sudo cp -r /home/marisembuh/marisembuh-fe/dist/* /var/www/html/marisembuh
